from pydantic import BaseModel, Field, field_validator


class PlannedTask(BaseModel):
    """
    One task generated by the LLM Planner.
    """

    id: str = Field(
        min_length=1,
        max_length=80,
    )

    description: str = Field(
        min_length=1,
    )

    dependencies: list[str] = Field(
        default_factory=list,
    )

    expected_output: str = ""

    priority: int = Field(
        default=1,
        ge=1,
        le=10,
    )

    @field_validator("id")
    @classmethod
    def validate_id(cls, value: str) -> str:
        value = value.strip().lower()

        if not value.replace("_", "").replace("-", "").isalnum():
            raise ValueError(
                "Task ID may contain only letters, numbers, '_' or '-'."
            )

        return value


class ExecutionPlan(BaseModel):
    """
    Complete DAG generated by the Planner.
    """

    goal: str = Field(
        min_length=1,
    )

    tasks: list[PlannedTask] = Field(
        min_length=1,
        max_length=30,
    )

    final_task_id: str

    reasoning: str = ""